/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Vista.VistaPrincipal.matrizMapa;
import static Vista.VistaPrincipal.objetosList;
import static Vista.VistaPrincipal.ladronCar;

import clases.CarroLadron;
import clases.EstacionDePolicia;
import clases.Vertice;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author Danii
 */
public class PanelVistaPrincipal extends javax.swing.JPanel {

    public static  int posInicialX;
    public static  int posInicialY;
    public static  int proporcion;

    /**
     * Creates new form PanelVistaPrincipal
     */
    public PanelVistaPrincipal() {
        initComponents();
        this.setSize(600, 600);
        posInicialX = 100;
        posInicialY = 10;
        proporcion = 40;
    }

    @Override
    protected void paintComponent(Graphics g) {
        pintarMapa(g);
        pintarObjetos(g);
        if (ladronCar!=null) {
          pintarLadron(g);  
        }
        
        repaint();
    }

    /**
     * *
     * Metodo para graficar el mapa sin aun paramerizar los objetos de este.
     *
     * @param g Componente grafico de la interfaz, donde se visualiaza
     */
    private void pintarMapa(Graphics g) {
        g.setColor(Color.black);
        g.fillRect(0, 0, 600, 600);
        if (matrizMapa != null && matrizMapa.length > 0) {
            for (int i = 0; i < matrizMapa.length; i++) {
                for (int j = 0; j < matrizMapa[i].length; j++) {
                    if (matrizMapa[i][j] == 1) {
                        g.setColor(Color.white);
                    } else {
                        g.setColor(Color.green);
                    }
                    g.fillRect(posInicialX + (proporcion * j), posInicialY + (proporcion * i), proporcion, proporcion);
                    g.setColor(Color.black);
                    g.drawRect(posInicialX + (proporcion * j), posInicialY + (proporcion * i), proporcion, proporcion);
                }
            }
        }
    }

    public Point obtenerMouse(int x, int y) {
        x = (x - posInicialX) / proporcion;
        y = (y - posInicialY) / proporcion;
        System.out.println("fila" + y + "columna" + x);
        return new Point(x, y);
    }

    /**
     * *
     * Metodo que grafica los objetos vertice
     *
     * @param g Componente grafico
     */
    private void pintarObjetos(Graphics g) {
        if (objetosList != null && objetosList.size() > 0) {
            for (int i = 0; i < objetosList.size(); i++) {
                if (objetosList.get(i).getImagen() != null) {
                    if (objetosList.get(i).getTipo().equalsIgnoreCase("EstacionP")) {
                        pintarPatrulla(objetosList.get(i), g);
                    }
                    g.drawImage(objetosList.get(i).getImagen(), posInicialX + objetosList.get(i).getColumna() * proporcion, posInicialY + objetosList.get(i).getFila() * proporcion, 50, 50, null);
                }
            }
        }
    }
    private void pintarPatrulla( Vertice vertice, Graphics g){
        EstacionDePolicia estacionP= (EstacionDePolicia)vertice.getContenedor();
        for (int i = 0; i < estacionP.getPatrullas().size(); i++) {
            //g.setColor(Color.blue);
            //g.fillRect((estacionP.getPatrullas().get(i).getColumna()*proporcion)+posInicialX, (estacionP.getPatrullas().get(i).getFila()*proporcion)+posInicialY, 20, 20);
            g.drawImage(estacionP.getPatrullas().get(i).getImagenes(),estacionP.getPatrullas().get(i).getxObjeto(), estacionP.getPatrullas().get(i).getyObjeto(), 40, 40, this);
        }
    }
    private void pintarLadron(Graphics g){
        g.drawImage(ladronCar.getImagenes(),ladronCar.getxObjeto(),ladronCar.getyObjeto(), 40, 40, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
