/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.Graphics;
import static Vista.VistaPrincipal.matrizMapa;

/**
 *
 * @author Danii
 */
public class PanelVistaPrincipal extends javax.swing.JPanel {

    private final int posInicialX;
    private final int posInicialY;
    private final int proporcion;

    /**
     * Creates new form PanelVistaPrincipal
     */
    public PanelVistaPrincipal() {
        initComponents();
        this.setSize(600, 600);
        this.posInicialX = 100;
        this.posInicialY = 10;
        this.proporcion = 40;
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(Color.white);
        g.fillRect(0, 0, 600, 600);
        if (matrizMapa.length > 0) {
            for (int i = 0; i < matrizMapa.length; i++) {
                for (int j = 0; j < matrizMapa[i].length; j++) {
                    if (matrizMapa[i][j] == 0) {
                        g.setColor(Color.green);
                    } else {
                        g.setColor(Color.black);
                    }
                    g.fillRect(posInicialX+(proporcion*j),posInicialY+(proporcion*i), proporcion, proporcion);
                }
            }
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
